name: drupal-ethereum
recipe: drupal9
services:
  appserver:
    webroot: web
    xdebug: debug
    config:
      php: .vscode/php.ini
    build_as_root:
      - apt update && apt install libgmp-dev -y && docker-php-ext-install gmp
